theme: jekyll-theme-minimal
title: 格物致知|言理以故
logo: /assets/img/logo.png
description: "欲求超胜，必先会通。<br>
              ——【明】徐光启<br>
              不因既明累推其未明，吾知奚至哉！<br>
              ——【欧】利玛窦（Matteo Ricci）"
github:
